pipeline:
  identifier: Build_vishravi2016_node_inventory_api_1783588091942
  name: Build node-inventory-api
  orgIdentifier: default
  projectIdentifier: mydemos
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: vishravi2016/node-inventory-api
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    shell: Sh
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: npm start
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
